language: python
python:
    - 2.7

before_install:
    - sudo apt-get install -y zookeeper

before_script:
    - "sudo /etc/init.d/zookeeper start"

after_script:
    - "sudo /etc/init.d/zookeeper stop"

install:
    - pip install .
    - pip install txzookeeper
    - pip install zc-zookeeper-static
services:
    - redis-server
script:
    - trial rhumba
